version: '3'

services:
  customer-oracle:
    image: n11com/oracle-xe-11g
    container_name: customer-oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - USERNAME=customer
      - PASSWORD=customer
    volumes:
      - ./docker-entrypoint-initdb.d.customer:/docker-entrypoint-initdb.d

  account-oracle:
    image: n11com/oracle-xe-11g
    container_name: account-oracle-db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - USERNAME=account
      - PASSWORD=account
    volumes:
      - ./docker-entrypoint-initdb.d.account:/docker-entrypoint-initdb.d



#  customer-postgres:
#    image: postgres
#    ports:
#    - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: customer
#    volumes:
#      - ./docker-entrypoint-initdb.d.customer:/docker-entrypoint-initdb.d
#    command:
#      - "postgres"
#      - "-c"
#      - "max_prepared_transactions=100"
#
#
#  account-postgres:
#    image: postgres
#    ports:
#    - "5433:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: account
#    volumes:
#      - ./docker-entrypoint-initdb.d.account:/docker-entrypoint-initdb.d
#    command:
#      - "postgres"
#      - "-c"
#      - "max_prepared_transactions=100"
#
