version: '3'

services:
  customer-oracle:
    image: oracle-xe:18c
    container_name: customer-oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - USERNAME=customer
      - PASSWORD=customer
      - ORACLE_PWD=Oracle18
    volumes:
      - ./docker-entrypoint-initdb.d.customer:/docker-entrypoint-initdb.d
      - ~/docker/oracle-xe01:/opt/oracle/oradata

  account-oracle:
    image: oracle-xe:18c
    container_name: account-oracle-db
    ports:
      - "1522:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - USERNAME=account
      - PASSWORD=account
      - ORACLE_PWD=Oracle18
    volumes:
      - ./docker-entrypoint-initdb.d.account:/docker-entrypoint-initdb.d
      - ~/docker/oracle-xe02:/opt/oracle/oradata
